name: escanear_qr
description: "A new Flutter project."
publish_to: 'none' 

version: 500.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  qr_code_scanner: ^1.0.1
  geolocator: ^11.0.0
  geocoding: ^2.2.0
  permission_handler: ^11.4.0
  firebase_core: ^2.30.0
  firebase_auth: ^4.17.3
  firebase_database: ^10.4.3
  firebase_storage: ^11.5.3
  url_launcher: ^6.2.5
  font_awesome_flutter: ^10.7.0
  image_picker: ^1.1.1
  http: ^0.13.6
  intl: ^0.18.0
  google_fonts: ^4.0.4
  shared_preferences: ^2.2.3
  webview_flutter: ^4.8.0
  flutter_image_compress: ^2.3.0
  qr_flutter: ^4.1.0  
  file_picker: ^8.0.0
  mime: ^1.0.5
  flutter_launcher_icons: ^0.14.4
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/primebox_logo.png
    - assets/images/default.png
    - assets/images/truck_illustration.png
    - assets/sound/sonido.mp3
    - assets/sound/sonidoerror.mp3

# ðŸ”¹ ConfiguraciÃ³n del Ã­cono de la app (fuera del bloque flutter:)
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/primebox_logo.png"
  min_sdk_android: 21
